@startuml Sistem Informasi Mahasiswa
     actor "User" as user

     node "Sistem Informasi Mahasiswa" {
          node "Model" as model
          node "Domain" as domain
          node "Contorller" as controller
          node "View" as view
          node "Service" as service
          node "Repository" as repository
     }

     database "MySQL" as mysql

     user --> controller : 1
     controller --> model : 2
     controller --> service : 3
     service --> repository : 4
     repository --> domain : 5
     repository --> mysql : 6
     controller --> view : 7
     controller --> user : 8
@enduml